import Head from 'next/head'
import { useState, useEffect } from 'react';
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from './Header';
import Movie from './Movie';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [ movies, setMovies ] = useState(null);

  useEffect(() => {
    fetch(`https://api.themoviedb.org/3/movie/popular?api_key=aab8c68a497683fd0e6dbd5d4b64a644`)
      .then(response => response.json())
      .then(data => {
        setMovies(data.results);
      })
  },[])

  console.log(movies)

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <main>
          <section className={styles.containerTitle}>
            <h1 className={styles.title}>Mais vistos</h1>
          </section>
          <div className={styles.main}>
          {
            movies?.map(movie => (
              <Movie 
                id={movie.id}
                title={movie.title}
                release_date={movie.release_date}
                poster_path={movie.poster_path}
              />
            ))
          }
          </div>
      </main>
    </>
  )
}
